### PR TITLE
travis: drop 0.10 and io.js, add stable

### PR DESCRIPTION
**Pull request by avindra**

### CODE REVIEW

**Comment by smali-kazmi** [comment]
@coveralls because test coverage don't cover few lines in code; so need to increase test coverage

**Comment by avindra** [comment]
@smali-kazmi : have you considered merging this?

**Comment by avindra** [comment]
@smali-kazmi any issues here?

**Comment by avindra** [comment]
@smali-kazmi closing this due to no response :/

**Pull request closed without merging**
